### ISSUE TITLE
Random Walk

### ISSUE THREAD

**Issue by jbensabat** [ufz/ogs#3018]
Hello 
I am new to OGS
I see that in version 5.x there is a class dealing with particle tracking 
can I find it in version 6 ?
thanks
jac

**Comment by endJunction** [comment]
Hello, we didn't reimplement all of the OGS-5 features in OGS-6; particle tracking is one of them.
I'd try to do the particle tracking in a post-processing step, *e.g.* with ParaView: there are a particle tracker and a streamline filters available.
